model_name: gemma3:12b
model_name_hf: google/gemma-3-12b-it
n_train: 800
options:
  temperature: 0.5
  top_p: 0.9
  num_ctx: 8192
reviewer:
  model_name: gpt-oss:20b
  options:
    think="high"
paths:
  in_file: data/raw/system_and_user_pairs_1k.jsonl
  out_dir: data/processed/
  out_file: data_1k.jsonl
  failed_response_file: failed.jsonl
  train_file: train.jsonl
  val_file: val.jsonl